version: "3.7"
services:
    db:
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3307:3306"
        env_file: ./mysql.env
        volumes:
            - ./data:/var/lib/mysql
    php:
        build: ./php-fpm
        ports:
            - "9000:9001"
        volumes:
            - ./app:/var/www/app:cached
            - ./logs/symfony:/var/www/app/var/log:cached
            - ./php-fpm/docs:/docs
            - ./logs/xdebug:/tmp/xdebug_log
        links:
            - db
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./app:/var/www/app:cached
