#index:
#    path: /
#    controller: App\Controller\DefaultController::index

controllers:
  resource: "../src/Controller/"
  type: annotation

security:
  resource: "../src/Security/"
  type: annotation
