twig:
    default_path: "%kernel.project_dir%/templates"
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        "%kernel.project_dir%/templates": AppTemplate
    form_themes: ["bootstrap_4_layout.html.twig"]
